service: aws-samples

plugins:
  - serverless-bundle
  - serverless-offline

custom:
  stage: ${opt:serviceStage, 'dev'}
  bundle:
    linting: false
    tsConfig: 'tsconfig.app.json'
  serverless-offline:
    httpPort: 3333
    noPrependStageInUrl: true

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs12.x
  memorySize: 256
  stage: ${self:custom.stage}
  endpointType: regional
  timeout: 20
  lambdaHashingVersion: 20201221 # removes deprecation warning (remove in serverless v3)
  apiGateway:
    shouldStartNameWithService: true # removes deprecation warning (remove in serverless v3)
  environment:
    APP_ENV: ${self:custom.stage}
    IS_PRODUCTION: '${file(./src/environments/config.${self:custom.stage}.json):is_production}'
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - "ssm:DescribeParameters"
            - "ssm:GetParameter*"
            - "ssm:GetParametersByPath"
          Resource: !Sub "arn:aws:ssm:${self:provider.region}:${AWS::AccountId}:parameter/application/services_products/*"

functions:
  ssm:
    handler: src/handlers/ssm.handler
    environment:
      SSM_PARAMTER: '/application/services_products/test/srv-products-test/password'
    events:
      - http:
          method: GET
          path: /ssm
